### ISSUE TITLE
use PythonCall?

### ISSUE THREAD

**Issue by ericphanson** [avik-pal/Wandb.jl#13]
Would you open to switching to PythonCall? I've found it easier to manage python dependencies that way. More info on PythonCall: https://discourse.julialang.org/t/ann-pythoncall-and-juliacall/76778

**Comment by avik-pal** [comment]
I can definitely consider it. Since Wandb.jl is currently in early stages, we can safely make these changes. I will try to prototype a version in the upcoming weeks and verify that everything is working.
