### ISSUE TITLE
Don't log during init

### ISSUE THREAD

**Issue by ericphanson** [avik-pal/Wandb.jl#14]
Would you be open to moving https://github.com/avik-pal/Wandb.jl/blob/379dc8f7b6164c9e0675fb35f031ac68011c2218/src/Wandb.jl#L9 to a separate function (maybe just a `Wandb.version()` ?). I'm starting to integrate Wandb into a codebase that only uses it *sometimes*, but since loading Wandb triggers the log message, the user always sees the message. IMO such messages are best left to "applications" (leaf-nodes of the pkg tree) rather than libraries.

**Comment by avik-pal** [comment]
Yeah I have been meaning to do it for a long time just keep forgetting :sweat:
