### ISSUE TITLE
Not all histograms appear correctly in wandb

### ISSUE THREAD

**Issue by rkube** [avik-pal/Wandb.jl#15]
Hi,
logging histograms with Wandb works, but not consistently. This pseudo-code:
```julia

ps = Flux.params(model)
for epoch in 1:num_epochs

    loss, back = Zygote.pullback(ps) do
        loss = ...
    end
    grads = back(one(loss))

    if (output_time)
        (x_test, y_test) = first(loader_test)
        y_real = model(x_test) |> cpu;

         grads_out = grads[ps[1]][:] |> cpu;

        log(wandb_logger, Dict("hist y_real" => Wandb.Histogram(y_real),
                                                  "grads" => Wandb.Histogram(grads))
    end
end
```

works for `y_real` but gives an error message for `grads` in the wandb dashboard:

![Sometimes it works](https://i.imgur.com/JHdUBxX.png)

![Sometimes it doesn't](https://i.imgur.com/67wEYqe.png)

Both `grads_out` and `y_real` are CPU vectors when they are passed to the logger:
```
julia> typeof(grads_D1)
Vector{Float32} (alias for Array{Float32, 1})

julia> typeof(y_real)
Matrix{Float32} (alias for Array{Float32, 2})

julia> size(grads_D1)
(216,)

julia> size(y_real)
(2, 128)
```

**Comment by avik-pal** [comment]
> "grads" => Wandb.Histogram(grads)

Seems to be a typo. You perhaps meant to pass `grads_out`?

**Comment by rkube** [comment]
Yeah, that's a typo. The actual training script is more complicated. The summary tab on the web interface actually shows the histogram data correctly, so it's probably an issue with the web interface and not this package.

**Comment by rkube** [comment]
I had to clear my workspace, using the menu in the lower left of the web interface

![Clear workspace](https://i.imgur.com/7op3Pp1.png)
