### ISSUE TITLE
Don't extend `Base.log`

### ISSUE THREAD

**Issue by ericphanson** [avik-pal/Wandb.jl#9]
As the code-comment says, it's bad practice. What's wrong with asking users to write `Wandb.log` if they want?

**Comment by avik-pal** [comment]
Yeah, I think I will remove the overload, and update the docs to ask people to do `Wandb.log`

**Comment by darsnack** [comment]
It seems the FluxTraining integration still uses `Base.log`. Is this intended?

**Comment by avik-pal** [comment]
No just an oversight. Could you send in a PR?
